### ISSUE TITLE
Rendu évaluation GPR1 - MenoudY

### ISSUE THREAD

**Issue by menoudyann** [menoudyann/GPR1-SocialNetwork#4]
[82c191d9718b1e9498ff0483780d10364a48709a](https://github.com/menoudyann/GPR1-SocialNetwork/commit/82c191d9718b1e9498ff0483780d10364a48709a) 

@NicolasGlassey 

Tous mes tests passent sauf le dernier ajouté. Je pense que cela est dû au fait que je ne fais pas remonter l'exception depuis la méthode subscribe dans le constructeur ce qui fait que le constructeur lui-même ne peut pas retourner cette erreur.

**Comment by NicolasGlassey** [comment]
@menoudyann 

Bonjour Yann,

J'ai pris en compte cette issue pour l'évaluation.

Bonne suite de week-end !
